kraj/meta-altera

conf/machine/stratix10swvp.conf
recipes-kernel/linux/linux-altera-configs.inc
recipes-kernel/linux/linux-altera.inc

-> New machine stratix10swvp
-> update linux-altera-configs to use the single defconfig provided for all arm64 platforms
-> updata linux-altera.inc to point to the correct dtb for s10swvp

Add support for the Stratix10 SW Virtual Platform

---

README.md

Added info on setting GCCVERSION and selecting the preferred kernels in README

Update README with information regarding kernel selection

---

recipes-kernel/linux/linux-altera_4.2.bb

i did test the build and it is working.

Add linux-altera_4.2 back per request from stefan

---

README.md

-> Move maintaners list to the bottom
-> Change titles to be more clear

Update README per kraj's comments

---

classes/image_types_socfpga.bbclass

Similarly to how other classes do when deploying images, add/replace the
symlink to the latest sdcard image file
Please, consider also backporting this to krogoth branch, where I've been currently using it for a while... Let me know if a separate PR is more suitable.

sdcard: add symlink to sdcard image artifact

---

classes/sdcard_image-socfpga.bbclass
conf/machine/arria5.conf
conf/machine/cyclone5.conf
recipes-bsp/u-boot/files/v2016.11/de0-nano-soc.env
recipes-bsp/u-boot/u-boot-mkenvimage_v2016.11.bb
recipes-bsp/u-boot/u-boot-socfpga-env.inc
recipes-bsp/u-boot/u-boot-socfpga_v2016.05.bb
recipes-bsp/u-boot/u-boot-socfpga_v2016.11.bb

Since the machine conf allows you to change uboot versions
you need to be able to change the sdcard creation setup

Only conditionally set SOCFPGA_SDIMG_PARTITION_COMMAND

---

recipes-bsp/u-boot/u-boot-socfpga_v2016.11.bb

This is all i meant to do.
Signed-off-by: Dalon Westergreen <dalon.westergreen@intel.com>

Add mkenvimage depend for v2016.11

---

recipes-bsp/u-boot/files/v2017.07/cyclone5-socdk.env
recipes-bsp/u-boot/files/v2017.07/de0-nano-soc.env
recipes-bsp/u-boot/u-boot-socfpga_v2017.07.bb

Add support for v2017.07 u-boot

---

classes/sdcard_image-socfpga.bbclass

Old dependency call was deprecated

Fix image class

---

classes/sdcard_image-socfpga.bbclass

fix deprecated dependency list

---

conf/machine/cyclone5.conf
conf/machine/include/socfpga.inc
conf/machine/stratix10.conf
recipes-bsp/u-boot/u-boot-socfpga_v2017.09.bb
recipes-kernel/linux/linux-altera-ltsi-rt_4.9.76.bb
wic/sdimage-cyclone5-arria5.wks
wic/sdimage-stratix10.wks

Stratix10:
-> Add support for S10 uboot
-> Cleanup stratix10.conf
-> Add v4.9.76-ltsi-rt kernel support
-> Add support for a wic generated sdcard image
Cyclone5/Arria5:
-> Add support for distroboot / extlinux.conf for u-boot setup
-> Add support for a wic generated sdcard image
--dalon

Various updates for stratix10 and cyclone5/arria5

---

conf/machine/include/socfpga.inc
recipes-bsp/u-boot/u-boot-socfpga_v2017.09.bb
recipes-kernel/linux/config/config_lbdaf.cfg
recipes-kernel/linux/linux-altera-ltsi-rt_4.9.76.bb
recipes-kernel/linux/linux-altera-ltsi_4.9.78.bb
recipes-kernel/linux/linux-altera_4.15.bb
wic/sdimage-cyclone5-arria5.wks

-> Update kernel and uboot SRCREVs
-> Fix Cyclone5/Arria5/Arria10 WIC issue with 0xa2 partition
-> Add CONFIG_LBDAF to resolve kernel mount issue with ext3 partitions
-> Update default distroboot config

Update and fixes

---

recipes-bsp/u-boot/u-boot-socfpga_v2018.03.bb

Add u-boot 2018.03

---

recipes-bsp/u-boot/u-boot-socfpga_v2017.09.bb
recipes-kernel/linux/linux-altera-configs.inc
recipes-kernel/linux/linux-altera.inc
recipes-kernel/linux/linux-altera_4.16.bb
recipes-kernel/linux/linux-altera_4.17.bb

-> Remove unsupported 4.15 kernel recipe
-> Add 4.17 Kernel recipe
-> Update License checksum for 4.17

Add 4.17 kernel

---

recipes-kernel/linux/linux-altera-ltsi-rt_4.9.76.bb
recipes-kernel/linux/linux-altera-ltsi_4.9.78.bb
recipes-kernel/linux/linux-altera_4.18.bb

Add 4.18 and update ltsi /ltsi-rt kernels

Rocko: cherry-pick kernel updates from master

---

recipes-kernel/linux/linux-altera-ltsi_4.14.73-ltsi.bb

Update kernel 4.14.73-ltsi to commit 3286950

Update kernel 4.14.73-ltsi to commit 3286950

---

README.md

This branch is no longer supported or maintained

Update README to indicate support status

---

README.md

Add brief description on targetting alternate boards
for a given machine.  In this example, specifically
mention the de0-nano-soc.

Readme: Update for board config

---

conf/machine/agilex.conf
recipes-bsp/u-boot/u-boot-socfpga_v2019.04.bb
recipes-kernel/linux/linux-altera-lts_5.4.bb
recipes-kernel/linux/linux-altera_5.4.bb

Add 5.4, 5.4-lts, update agilex defconfig

Update to kernel, uboot, agilex support

---

recipes-bsp/u-boot/u-boot-socfpga_v2019.10.bb

u-boot: update to v2019.10

---

conf/layer.conf

Signed-off-by: Khem Raj <raj.khem@gmail.com>

layer.conf: Mark dunfell compatible

---

conf/machine/cyclone5.conf

Fixes #181 
Signed-off-by: Christian Haettich <feddischson@gmail.com>

Add de10-nano configuration

---

recipes-bsp/u-boot/u-boot-socfpga_v2019.10.bb

u-boot-socfpga_v2019.10: update to latest SRCREV

---

recipes-kernel/linux/linux-altera-lts_5.4.23.bb

linux-altera-lts: 5.4.23: update to latest SRCREV

---

recipes-kernel/linux/linux-altera-lts_5.4.34.bb

kernel: add 5.4.34-lts branch

---

recipes-bsp/u-boot/u-boot-socfpga_v2019.10.bb

u-boot-socfpga: update to latest HEAD

---

recipes-bsp/u-boot/u-boot-socfpga_v2020.04.bb

u-boot-socfpga: add socfpga_v2020.04 branch

---

recipes-kernel/linux/linux-altera_5.7.bb

kernel: 5.7: fix license file checksum

---

conf/layer.conf

Signed-off-by: Khem Raj <raj.khem@gmail.com>

layer.conf: Add hardknott to supported releases

---

recipes-bsp/u-boot/u-boot-socfpga-common.inc

RPROVIDES still used the old syntax.

Use new syntax for RPROVIDES

---

conf/machine/arria10.conf
conf/machine/arria5.conf
conf/machine/cyclone5.conf

"default" is expected to be part of OVERRIDES, and has to follow new
override syntax.
Fixes https://github.com/kraj/meta-altera/issues/234

machine: fix "default" overrides
