- recipes-kernel/linux/linux-altera.inc
Made changes recommended in http://www.yoctoproject.org/docs/1.8/ref-manual/ref-manual.html#migration-1.8-kernel-build-changes to ensure make
runs in the proper directory.
This allows other tools such as lttng and perf to find required files in work-shared/kernel-source
> Build kernels properly in YP1.8

- recipes-bsp/u-boot/u-boot-socfpga.inc
- recipes-kernel/linux/linux-altera-dev.bb
- recipes-kernel/linux/linux-altera-ltsi-dev.bb
- recipes-kernel/linux/linux-altera-ltsi_3.10.bb
- recipes-kernel/linux/linux-altera_4.0.bb
- recipes-kernel/linux/linux-altera_4.1.bb
- recipes-kernel/linux/linux-altera_4.2.bb
Just noticed the cyclone5 / arria5 uboot recipe still pointed to rocketboards git repo
> Change uboot git repo to new github location

- recipes-kernel/linux/linux-altera.inc
- recipes-kernel/linux/linux-altera_4.0.bb
- recipes-kernel/linux/linux-altera_4.1.bb
- recipes-kernel/linux/linux-altera_4.2.bb
-> Add de0 board device tree to default list
-> disable de0 dts for 4.0/4.1/4.2 kernels
> Update devicetree list for cyclone5 to include de0 board

- recipes-kernel/linux/linux-altera-ltsi-rt_3.10.bb
- recipes-kernel/linux/linux-altera-ltsi_3.10.bb
- recipes-kernel/linux/linux-altera_4.0.bb
- recipes-kernel/linux/linux-altera_4.1.bb
- recipes-kernel/linux/linux-altera_4.2.bb
-> Remove 3.10 ltsi / 3.10 ltsi-rt recipes, 4.1 ltsi is available
-> Remove 4.0 / 4.1 / 4.2 kernels
These kernels are no longer maintained, or developed and actually have build issues that will not be resolved.
> Remove kernels that are no longer supported or in development

- recipes-kernel/linux/linux-altera-ltsi-rt_3.10.bb
- recipes-kernel/linux/linux-altera-ltsi_3.10.bb
-> These currently do not compile with the 5.2 toolchain
-> You must use the 4.9 toolchain
-> set ANGSTROM_GCC_VERSION_arm = "linaro-4.9%" in your local.conf
> Add back old LTSI kernels

- conf/machine/arria5.conf
- conf/machine/cyclone5.conf
- recipes-bsp/u-boot/u-boot-socfpga_2013.01.01.bb
- recipes-bsp/u-boot/u-boot-socfpga_2016.03.bb
1) Remove 2013.01.01 u-boot which is only used
for cyclone5/arria5. cyclone5/arria5 are fully
supported in mainline uboot
2) Add recipe for mainline uboot supporting socfpga
cyclone5 / arria5 based kits.
> Add support for mainline uboot for cyclone5 / arria5 devices

- classes/image_types_socfpga.bbclass
- conf/machine/arria5.conf
- conf/machine/cyclone5.conf
1) Disable sdcard generation using UBOOT_CONFIG parameter
2) Fix type in sdcard class
SDCard generation still isnt working quite right.  If
IMAGE_FSTYPES += " sdcard" is added, the sdcard image
is created but the uboot-config should automatically
add sdcard creation when the UBOOT_CONFIG selected
looks like "socfpga_cyclone5_socdk,sdcard".
TBD:
1) Add uboot env customization based on
selected uboot config
2) Fix sdcard generation issue
> SDcard fixes

- recipes-kernel/linux/linux-altera-ltsi-dev_4.1.22.bb
- recipes-kernel/linux/linux-altera-ltsi-dev_4.1.bb
- recipes-kernel/linux/linux-altera-ltsi-rt-dev_4.1.22.bb
- recipes-kernel/linux/linux-altera-ltsi-rt_4.1.22.bb
- recipes-kernel/linux/linux-altera-ltsi-rt_4.1.bb
- recipes-kernel/linux/linux-altera-ltsi_4.1.22.bb
- recipes-kernel/linux/linux-altera-ltsi_4.1.bb
Missed the ".=" rather than the ":="
--dalon
> Fix error in FILESEXTRAPATH assignment in ltsi kernel recipes

- recipes-kernel/linux/linux-altera-ltsi_4.1.22.bb
- recipes-kernel/linux/linux-altera_4.6.bb
this fixes a problem with devicetree overlays and bridge resets
> Update 4.1.22 ltsi and 4.6 SRCREV to latest hash tag

- recipes-kernel/linux/linux-altera_4.4.bb
commit: 0e938a8fafccb73ad70781ed62abda2b554eafb4 is not included in socfpga-4.4
branch. Therefore, build of linux-altera_4.4 recipe will fail.
This sets 84eb65f84ea7a15cd73766fb16e6a868dc7a734b is current HEAD of
socfpga-4.4 to SRCREV.
Signed-off-by: Nobuhiro Iwamatsu <nobuhiro.iwamatsu.kw@hitachi.com>
> linux-altera: 4.4: fix wrong SRCREV

- classes/image_types_socfpga.bbclass
Similarly to how other classes do when deploying images, add/replace the
symlink to the latest sdcard image file
Signed-off-by: Andrea Galbusera <gizero@gmail.com>
> sdcard: add symlink to sdcard image artifact

- recipes-kernel/linux/linux-altera.inc
Commit 0eacf03de18b7eeb3460a4d102dd5932cd73cd06 in poky master introduced
a new QA test that linux-altera recipes are currently failing with:
ERROR: linux-altera-ltsi-4.1.22+gitAUTOINC+76bdba2700-r0
do_kernel_version_sanity_check: Package Version (4.1.22+gitAUTOINC+76bdba2700)
does not match of kernel being built (4.1.22-ltsi). Please update the PV
variable to match the kernel source.
Append ${LINUX_VERSION_SUFFIX} to PV to match version information in kernel's
Makefile.
This is a naive solution that ends up with names like linux-altera-ltsi-4.1.22-ltsi+gitAUTOINC+76bdba2700-r0. Feel free to drop if you know a cleaner fix.
> linux-altera: fix QA error on kernel PV mismatch

- recipes-bsp/u-boot/u-boot-socfpga_v2016.05.bb
- recipes-bsp/u-boot/u-boot-socfpga_v2016.11.bb
No longer removing the common include for u-boot-socfpga, but cleaning up v2016.05 to remove extraneous 10m50 additions.  The files being added for the 10m50 are not needed.
Signed-off-by: Dalon Westergreen <dalon.westergreen@intel.com>
> u-boot-socfpga: Remove unnecessary 10m50 additions in v2016.05

- recipes-bsp/u-boot/files/v2014.10/fix-build-error-under-gcc6.patch
- recipes-bsp/u-boot/u-boot-socfpga_v2014.10.bb
- recipes-bsp/u-boot/u-boot-socfpga_v2016.05.bb
- recipes-bsp/u-boot/u-boot-socfpga_v2016.11.bb
Patch references by Khem worked like a charm, also clean up some 10m50 stuff that isnt needed.
> Add support to fix arria10 u-boot-socfpga v2014.10 build with gcc6

- classes/sdcard_image-socfpga.bbclass
Change sdcard creation to use the fstype in the build rather
than in the deploy dir.  Also, put created image in the build
dir rather then the deploy dir direcly.  I believe this to be
the cause of the stale or non-working root filesystem
> Fix sdcard creation class issue with using stale content

- classes/sdcard_image-socfpga.bbclass
- recipes-bsp/u-boot/files/v2016.11/cyclone5-socdk.env
- recipes-bsp/u-boot/u-boot-socfpga-env.inc
- recipes-bsp/u-boot/u-boot-socfpga_v2016.11.bb
create uboot environment images to populate the sdcard
images.  This allows non-default uboot environments to be
used without the need for changing / patching uboot
Initially add de0-nano-soc environment
> add support to generate uboot environment images

- classes/sdcard_image-socfpga.bbclass
- conf/machine/arria5.conf
- conf/machine/cyclone5.conf
- recipes-bsp/u-boot/files/v2016.11/cyclone5-socdk.env
- recipes-bsp/u-boot/files/v2016.11/de0-nano-soc.env
- recipes-bsp/u-boot/u-boot-mkenvimage_v2016.11.bb
- recipes-bsp/u-boot/u-boot-socfpga-common.inc
Revert sdcard creation to old partition scheme
-> using p1 for the 0xa2 partition results in not being able to mount the fat partition on windows
Change env for de0 and c5 board to reflect the above
-> this should be short term, distro boot should remove the need for playing with the uboot env
> Fixes to get ready for extlinux.conf / distro_boot support

- classes/sdcard_image-socfpga.bbclass
I found a need to have additional files copied to the fat partition on the sdcard. Specifically it may be necessary to place an fpga bitstream on the sdcard to allow uboot to use it during boot to configure the fpga.  This adds support for arbitrarily copying files from the deploy directory to the fat partition on the sdcard by adding SOCFPGA_SDIMG_EXTRA_FILES to local.conf or the machine configuration.
SOCFPGA_SDIMG_EXTRA_FILES lists any files to be added from
the DEPLOYDIR to the FAT partition of the sdcard image
Signed-off-by: Dalon Westergreen <dalon.westergreen@intel.com>
> Add support for extra files in sdcard image

- recipes-bsp/u-boot/files/0001-Fix-native-build-by-using-env-variables.patch
- recipes-bsp/u-boot/u-boot-mkenvimage_v2016.11.bb
- recipes-bsp/u-boot/u-boot-socfpga_v2016.11.bb
Mainly fix the u-boot build by:
- changing u-boot-mkenvimage to use $(CC) instead of cc
- adding bc-native to u-boot-socfpga due to RS-sysroot in YP
Signed-off-by: Jan-Simon Möller <jsmoeller@linuxfoundation.org>
> Fix build with YP pyro

- recipes-bsp/u-boot/u-boot-socfpga-common.inc
For Stratix10, U-Boot SPL is placed in the FPGA
image.  To do this, it must be in an ihex format.
> Generate U-Boot SPL hex image

- wic/sdimage-cyclone5-arria5.wks
- wic/sdimage-stratix10.wks
wic modifies /etc/fstab to add mount points
listed in the wks file.  We do not want the fat
partition mounted by default
> Fix wic mount of sdcard fat partition

- classes/sdcard_image-socfpga.bbclass
Name had to change from  do_image_socfpga-sdimg[depends] to do_image_socfpga_sdimg[depends] . And we need sync (coreutils) as well.
> Another fix for the socfpga image class

- conf/machine/arria5.conf
sdcard image class is no longer valid, remove the INHERIT
for the class
> Remove sdcard class INHERIT from arria5 machine conf

- conf/machine/include/socfpga.inc
- recipes-bsp/u-boot/files/v2016.11/cyclone5-socdk.env
- recipes-bsp/u-boot/files/v2016.11/de0-nano-soc.env
- recipes-bsp/u-boot/files/v2017.07/cyclone5-socdk.env
- recipes-bsp/u-boot/files/v2017.07/de0-nano-soc.env
- wic/sdimage-cyclone5-arria5.wks
This would allow to later on resize the rootfs
partition inside of the Linux if the storage media
used is originally bigger than the image itself. It
would effectively allow to utilize the entire storage
media from the Linux OS on the device.
Signed-off-by: Andrey Zhizhikin <andrey.z@gmail.com>
> Exchange A2 and ext4 rootfs partitions in wic image

- conf/layer.conf
- conf/machine/cyclone5.conf
- recipes-bsp/u-boot/u-boot-socfpga-common.inc
- recipes-bsp/u-boot/u-boot-socfpga_v2016.05.bb
- recipes-bsp/u-boot/u-boot-socfpga_v2016.11.bb
- recipes-bsp/u-boot/u-boot-socfpga_v2017.07.bb
- recipes-bsp/u-boot/u-boot-socfpga_v2017.09.bb
- recipes-bsp/u-boot/u-boot-socfpga_v2018.03.bb
- recipes-bsp/u-boot/u-boot-socfpga_v2018.05.bb
- recipes-bsp/u-boot/u-boot-socfpga_v2019.01.bb
This pull request supersedes the pull request #108 submitted to thud branch. As stated in original pull request, following problematic is resolved:
> Current U-Boot version v2017.09 does not successfully compiles with the thud branch of Yocto due to conflict with libfdt headers are presented twice: once in sysroot and once in u-boot tree itself.
> 
> The version v2018.05 resolves this issue, and therefore should be used with thud branch further.
> 
> 
Mainline build has been verified using Terasic SoCkit, following version information received from the board:
`root@cyclone5:~# uname -a
Linux cyclone5 4.14.73-ltsi-altera #1 SMP Wed Jan 9 08:35:08 UTC 2019 armv7l armv7l armv7l GNU/Linux
root@cyclone5:~# cat /etc/issue
Poky (Yocto Project Reference Distro) 2.6+snapshot \n \l`
> mainline: update u-boot version to 2019.01 for cyclone5

- conf/machine/cyclone5.conf
- recipes-bsp/u-boot/u-boot-socfpga-common.inc
- recipes-bsp/u-boot/u-boot-socfpga_v2016.05.bb
- recipes-bsp/u-boot/u-boot-socfpga_v2016.11.bb
- recipes-bsp/u-boot/u-boot-socfpga_v2017.07.bb
- recipes-bsp/u-boot/u-boot-socfpga_v2017.09.bb
- recipes-bsp/u-boot/u-boot-socfpga_v2018.03.bb
- recipes-bsp/u-boot/u-boot-socfpga_v2018.05.bb
- recipes-bsp/u-boot/u-boot-socfpga_v2019.01.bb
Current U-Boot version v2017.09 does not successfully compiles with the thud branch of Yocto due to conflict with libfdt headers are presented twice: once in sysroot and once in u-boot tree itself.
The version v2018.05 resolves this issue, and therefore should be used with thud branch further.
Build has been verified using Terasic SoCkit.
> Update U-Boot version to be compatible with thud branch

- recipes-kernel/linux/linux-altera_4.20.bb
- recipes-kernel/linux/linux-altera_5.0.bb
altera-opensource/linux-socfpga does have Branches for 4.20 and 5.0 i just wanted to add them.
> Add socfpga kernel 4.20 and kernel 5.0

- recipes-kernel/linux/linux-altera.inc
The commit
202eb5481421 ARM: dts: socfpga: Rename socfpga_cyclone5_de0_{sockit,nano_soc}
on the linux-altera repository renamed the socfpga_cyclone5_de0_sockit.dtb devicetree
to socfpga_cyclone5_de0_nano_soc.dtb.
Rename it also here
> linux-altera: rename socfpga_cyclone5_de0_{sockit,nano_soc}

- conf/machine/stratix10.conf
Remove reference to auto-serial-console as it is in
meta-linaro which is not needed.  Add SERIAL_CONSOLES
to enable a terminal on ttyS0.
> stratix10: update machine conf to add serial consoles

- conf/layer.conf
Warrior specific changes are needed, and as a result
sumo and thud support must be disabled.
> Only support Warrior in LAYERS_COMPAT

- recipes-bsp/u-boot/files/v2019.07/0001-fpga-arria10-Fix-error-in-fpga-pin-configuration.patch
- recipes-bsp/u-boot/u-boot-socfpga_v2019.07.bb
Update u-boot to release tag and add fix for arria10 to
release fpga routed HPS peripherals properly.
> u-boot: update to 2019.07 release and add patch for a10 fix

- conf/machine/cyclone5.conf
Without updating the reference to the write dtb on the kernel (as proposed by this PR) I was not able to compile yocto with this meta-altera
> Update de0 nano dtb reference

- conf/machine/cyclone5.conf
Wrong file socfpga_cyclone5_de0_nano_soc.dtb name in Kernel Device Tree
> Fix file name in Kernel Device Tree

- README.md
Only supported/maintained u-boot/kernel versions are
available on github.com/altera-opensource.
> Update README to reflect u-boot / kernel policy

- recipes-bsp/u-boot/u-boot-socfpga_v2019.10.bb
Update to 7298985146c70ca8af8d43dd963b3e8aa3900d87 in 2019.10 branch
> u-boot: Update 2019.10 to latest release

- conf/machine/arria10.conf
1. Changed page size for NAND flash to a supported page size
2. Added options for mkfs.jffs2 to remove cleanmarker and squash all user permission to root.
The changes in the machine conf have been tested on arria10 NAND flash and proven working.
> Update on arria10 machine config

- README.md
- recipes-bsp/u-boot/u-boot-socfpga-common.inc
- recipes-bsp/u-boot/u-boot-socfpga_v2019.04.bb
- recipes-bsp/u-boot/u-boot-socfpga_v2019.10.bb
- recipes-bsp/u-boot/u-boot-socfpga_v2020.04.bb
This is similar approach to the kernel recipe where we have one common include file for common variables.
This approach can help us to build u-boot from different repo by setting UBOOT_REPO in conf/local.conf.
> U-boot Recipe Changes

- wic/sdimage-arria10.wks
- wic/sdimage-cyclone5-arria5.wks
New u-boot version has its binary aligned to start from 2048 boot sector.
> wic: resolve boot issue when using wic images

- recipes-bsp/arm-trusted-firmware/arm-trusted-firmware.inc
Make SRC_URI composed from ATF_REPO, ATF_BRANCH and ATF_PROT
as we have use case to change the ATF_REPO location and branch.
> atf: update recipe SRC_URI structure

- recipes-kernel/linux/linux-altera-ltsi/0001-Rename-de0_sockit-devicetree-to-de0_nano_soc.patch
- recipes-kernel/linux/linux-altera-ltsi_4.14.130.bb
|   CHK     scripts/mod/devicetable-offsets.h
| make[3]: *** No rule to make target 'arch/arm/boot/dts/socfpga_cyclone5_de0_nano_soc.dtb'.  Stop.
| arch/arm/Makefile:343: recipe for target 'socfpga_cyclone5_de0_nano_soc.dtb' failed
Signed-off-by: Alessio Igor Bogani <alessio.bogani@elettra.eu>
> Fix 4.x kernel build

- recipes-kernel/linux/linux-altera-lts_5.4.bb
SRCREV needed to be upgraded to 5.4.84 as well
Fixes #219
Signed-off-by: Khem Raj <raj.khem@gmail.com>
> linux-altera-lts-5.4: Fix SRCREV
